name: tidytuesday-env
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.4.26=h4c7d964_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - liblzma=5.8.1=h2466b09_1
  - libmpdec=4.0.0=h2466b09_0
  - libsqlite=3.49.2=h67fdade_0
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.5.0=ha4e3fda_1
  - pip=25.1.1=pyh145f28c_0
  - python=3.13.3=h261c0b1_101_cp313
  - python_abi=3.13=7_cp313
  - tk=8.6.13=h2c6b04d_2
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.3=h2b53caa_26
  - vc14_runtime=14.42.34438=hfd919c2_26
  - pip:
      - attrs==25.3.0
      - certifi==2025.4.26
      - cfgv==3.4.0
      - charset-normalizer==3.4.2
      - detect-secrets==1.5.0
      - distlib==0.3.9
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - identify==2.6.12
      - idna==3.10
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - nbformat==5.10.4
      - nbstripout==0.8.1
      - nodeenv==1.9.1
      - platformdirs==4.3.8
      - pre-commit==4.2.0
      - pywin32==310
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - rpds-py==0.25.1
      - ruff==0.11.11
      - traitlets==5.14.3
      - urllib3==2.4.0
      - virtualenv==20.31.2
